### ISSUE TITLE
Supported models

### ISSUE THREAD

**Issue by mo8Zomo0** [jarekj9/mitempjj#10]
Hi! 
Do I assume right that this does only work with the older round AAA battery driven ones
or also the newer square CR2032 driven ones?

**Comment by jarekj9** [comment]
Hi,
I do have a working version, that supports the new square one (LYWSD03MMC),
that is flashed with custom rom, but its a bit twisted and decided it was
too complex to publish.
Take a look on this : https://github.com/pvvx/ATC_MiThermometer
The tool allows to flash LYWSD03MMC with custom firmware, then Device will
advertise temprature and humidity with unencrypted BT low energy
advertisements (by default it can't do that).

pt., 3 wrz 2021 o 03:54 mek ***@***.***> napisał(a):

**Comment by mo8Zomo0** [comment]
ok, thx!

**Comment by jarekj9** [comment]
If you're still interested, I made it working with new square sensors, but
only on custom firmware : )

pt., 3 wrz 2021 o 03:54 mek ***@***.***> napisał(a):
